### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by munishchouhan** [mardurhack/quickhpc#1]
Is it possible to extract the time when cache miss occurs using this tool?

**Comment by elchiapp** [comment]
By extracting the time you mean understand at what CPU tick it happened? Extracting the relative time is possible, you can then compare it with the starting time to understand "when" the process caused that cache miss. But saying "there was a cache miss at 3:45 PM" is more complicated. Also you should not put any code related to time handling in quickhpc itself or the time resolution will drop greatly.

**Comment by munishchouhan** [comment]
Thanks a lot for your reply
can you explain the process of extracting relative time using quickhpc?

**Comment by elchiapp** [comment]
To extract relative time you can just use something like `clock_gettime` to measure the time difference (up to your clock's resolution) between two points in time. But you should modify and recompile quickhpc to do so. Closing this unless you have further ideas.
