### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by shujamughal** [mardurhack/quickhpc#3]
sbaig@bscpower8n1:~/quickhpc/src$ make
gcc -I/apps/PAPI/SRC/papi-5.5.0/src -I/apps/PAPI/SRC/papi-5.5.0/src -I/apps/PAPI/SRC/papi-5.5.0/src/testlib  -g -c config.c
gcc  -I/apps/PAPI/SRC/papi-5.5.0/src -I/apps/PAPI/SRC/papi-5.5.0/src -I/apps/PAPI/SRC/papi-5.5.0/src/testlib  -g -Wall quickhpc.c \
    /apps/PAPI/SRC/papi-5.5.0/src/testlib/do_loops.o /apps/PAPI/SRC/papi-5.5.0/src/testlib/test_utils.o /apps/PAPI/SRC/papi-5.5.0/src/testlib/dummy.o \
    /apps/PAPI/SRC/papi-5.5.0/src/libpapi.a \
    config.o -o ../quickhpc
/apps/PAPI/SRC/papi-5.5.0/src/libpapi.a(linux-cuda.o): In function `papicuda_shutdown_component':
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:740: undefined reference to`dlclose'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:741: undefined reference to `dlclose'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:742: undefined reference to`dlclose'
/apps/PAPI/SRC/papi-5.5.0/src/libpapi.a(linux-cuda.o): In function `papicuda_linkCudaLibraries':
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:194: undefined reference to`dlopen'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:196: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:197: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:198: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:199: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:200: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:201: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:202: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:203: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:204: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:205: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:206: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:207: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:208: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:209: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:211: undefined reference to `dlopen'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:213: undefined reference to`dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:214: undefined reference to `dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:215: undefined reference to`dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:216: undefined reference to `dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:217: undefined reference to`dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:218: undefined reference to `dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:220: undefined reference to`dlopen'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:222: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:223: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:224: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:225: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:226: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:227: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:228: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:229: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:230: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:231: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:232: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:233: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:234: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:235: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:236: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:237: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:238: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:239: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:240: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:241: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:242: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:243: undefined reference to`dlerror'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:244: undefined reference to `dlsym'
/apps/PAPI/SRC/papi-5.5.0/src/components/cuda/linux-cuda.c:245: undefined reference to`dlerror'
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'all' failed
make: **\* [all] Error 1
sbaig@bscpower8n1:~/quickhpc/src$

**Comment by elchiapp** [comment]
Hi, just tested compiling with PAPI 5.5.0 on a fresh Ubuntu 16.04 Docker container and everything went perfectly fine. Please make sure that: 0) you installed the `build-essential` package, 1) you compiled PAPI successfully, 2) you set the `PAPI_DIRECTORY` variable correctly in quickhpc's Makefile.

I'm pushing the container's image to https://hub.docker.com/r/lambdacomplete/quickhpc-sample (will take a while to upload so wait a few hours). Everything is in `/quickhpc`.

**Comment by AbhijittDhavlle** [comment]
Hello, 
I tried visiting the link "https://hub.docker.com/r/lambdacomplete/quickhpc-sample" but, it does not show up any content. Can you please email me the directory? I am working on a Grad School project that requires the QuickHPC tool. Thanks !! Help is appreciated !!

**Comment by elchiapp** [comment]
Please look at https://hub.docker.com/r/lambdacomplete/quickhpc-sample/, it's ready to be used with Docker. Everything you need is in this repository.

Also please notice that any usage of QuickHPC must be authorized and credited. Thanks.

**Comment by AbhijittDhavlle** [comment]
Thanks. But, I have one more quick question: the instructions on the github
page says that I have to pass PID of the process I want to read performance
counters for by prepending with '-a PiD' while running the tool ,but, I
want to run the tool along with my compiled C program object file by
passing the name of the file itself like perf tool does. How do I do that??
Because my c program takes seconds to complete and exit and hence, running
the program first and then supplying the tool with its PID is not possible.
And I tried running the tool by directly passing the c object file name and
it throws an error.
Kindly help me on this.


thanks

-Abhijitt

**Comment by elchiapp** [comment]
> And I tried running the tool by directly passing the c object file name and
it throws an error.

Of course...Processes and object files are two completely different entities. It is very much possible to supply a program with the PID of a process that runs for a few seconds. In fact there is a clear example in the README of QuickHPC itself.

**Comment by AbhijittDhavlle** [comment]
![screenshot from 2018-11-13 17-22-35](https://user-images.githubusercontent.com/26362620/48446989-c30fae80-e768-11e8-8fcd-7b65ad16f6a9.png)

Hello, thank you for pointing that to me, I was able to figure it out ,but, when I do everything as per the Readme document it throws me an error. I have attached a screenshot of the error as a file here. Kindly let me know what I did incorrect here and if so, how to fix it. 

Also, when I go to '/quickhpc/PAPI/src/utils'  and run 'papi_component_avail', it gives me what it looks in the attached pic#2 - it shows that the events are disables whereas on my actual local host system, 'papi_component_avail' works fine and events are enabled. 
![screenshot from 2018-11-13 17-48-11](https://user-images.githubusercontent.com/26362620/48448458-1be14600-e76d-11e8-9542-da72689c8b4d.png)


Thanks!!
Regards
-Abhijitt

**Comment by AbhijittDhavlle** [comment]
Hello Marco,
Thanks for pointing that out to me. I read the readme file and could make some changes to the command and its arguments so I could run both my program and collect performance counters. But, the problem now is when I try to run the program it gives me an error as attached below in screenshot #1 where it does not recognize the events I specified in the ‘conf’ file.

Also, just to make sure that ‘perf_events’ are enabled on my system, I ran ‘papi_component_avail’ from inside the docker container and it gives me the output in screenshot#2 image attached below – because on my local host the same ‘papi_component_avail’ instruction gives an output where both the events are printed under the active components section and it allows me to get performance counters. 

Kindly find the attached screenshots of the terminals and please let me know asap what should be done to fix this new issue. 

Thank You
Regards
Abhijitt Dhavlle
