### ISSUE TITLE
Lower resolution than 3 microseconds

### ISSUE THREAD

**Issue by akashgupta97** [mardurhack/quickhpc#8]
Hi,

I am working on a research project where I need to sample HPCs during the execution of cpp programs. The running time for each cpp program is lower than 3 microseconds (around 0.003 microseconds). I tried passing some lower resolutions (0.3, 0.03, etc.) to the quickhpc tool. I do receive more samples but it seems that it has a bottleneck at around 1 microsecond.  Do you know if I can achieve the above task using quickhpc i.e. sampling at nanoseconds rate, and if not is there any other tool to do so?

**Comment by elchiapp** [comment]
Hi, this depends on your architecture and on a lot of things that are outside of quickhpc's control. Let me know if you achieve higher resolution on different hardware. Thanks.
