### ISSUE TITLE
quickhpc not compatible with PAPI version > 5.5

### ISSUE THREAD

**Issue by akashgupta97** [mardurhack/quickhpc#9]
I am trying to run PAPI but the make command for quickhpc (4th step in Build) is throwing an error. Since my system requires to install PAPI version > 5.5 as I get other compatibility errors when I try to configure PAPI version <=5.5.  Is there any way to solve this? 

My configuration - 
gcc version is - GCC 9.2.0.
Linux kernel version -  Linux 3.10.0-957.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)

I get the below error - 

config.h:11:21: error: ‘PAPI_MAX_STR_LEN’ undeclared here (not in a function); did you mean ‘MAX_STR_LEN’?
11 | #define MAX_STR_LEN PAPI_MAX_STR_LEN

I tried replacing MAX_STR_LEN to 128 (as defined the value of PAPI_MAX _STR_LEN), I again get the following error -

gcc: error: ../papi-6.0.0.1/src/testlib/dummy.o: No such file or directory

**Comment by nivi1501** [comment]
Please let me know how you solved this issue.

**Comment by Incapamentum** [comment]
Hi,

Also encountered this exact issue. I snooped around a bit and discovered that someone [forked](https://github.com/zechenghe/quickhpc) the repo and fixed the bugs. 

I am running on PAPI-5.6.0 on Ubuntu 18.04 with a Zen2 chip. Hope this info helps!

**Comment by elchiapp** [comment]
Merged the fork upstream so you can keep using this repo. Thank you.
